### ISSUE TITLE
Running as system user

### ISSUE THREAD

**Issue by trilok54660** [stchan/PdfScribe#17] opened 2019-07-12 04:16 UTC
Redmon redirecting to .exe as 'System' user. and it's running in the background. Exe is running is background so not working

**Comment by stchan** [comment] 2019-07-15 02:36
I've never had this happen to me, but found this stackoverflow thread:

https://stackoverflow.com/questions/48208509/in-windows-10-redirect-port-monitor-redmon-run-as-user-doesnt-work?rq=1

It looks like this happens on Windows 10 sometimes, but no one has identified what the cause is. If anyone has any info or insights, I'd appreciate a comment here.

**Comment by stchan** [comment] 2019-07-15 02:38
possibly related to #16

**Comment by gbengustic** [comment] 2019-07-18 11:45
Am also having this issue on a windows 10 machine. The PDFScribe process starts suspended as system user and then disappears without generating a PDF output file.

**Comment by stchan** [comment] 2019-08-08 19:16
Confirmed as of Windows 10, version 1903, Redmon no longer seems to be able to launch PdfScribe.exe as the interactive user. I found this to be true on systems upgraded to 1903 with PdfScribe already installed, and for new PdfScribe installs on 1903. I will update the README to list this as a known issue, and begin looking into what can be reasonably done to fix this (if anything at all).

**Comment by drseussofporn** [comment] 2019-08-22 20:33
Was related to #16 ; I have successfully installed clawmon and configured it to pipe the output to PDFScribe.exe and everything works as expected. It looks like some work just needs to be done on the implementation of redmon for PDFScribe.

**Comment by stchan** [comment] 2019-09-02 19:55
Just another datapoint - I have a Win 10 install that just upgraded to 1903 last week, and is not exhibiting this issue. At this point, I don't know why.

**Comment by rrrr98** [comment] 2019-09-17 07:25
I tried this on two different computer using Win 10  with same version 1903. This work well on one computer but not on the other one. The issue is same as reported before.

**Comment by agustindelaroza** [comment] 2020-01-07 11:36
I confirm this issue is still present. In my case, only UWP application that use the new print dialog are failing. All other aplications using the old-school print dialog seem to work just fine.

**Comment by stchan** [comment] 2020-01-07 18:13
I've never been able to lock down a specific set of
conditions/configurations that can cause this - some people report it never
working, some say everything still works fine, and others like yourself
find that the problem only happens under specific conditions. I haven't had
any time to work on this project lately, but when I come back around, the
plan is to replace Redmon with a different port monitor (like mfilemon,
which has been reported to work). If that doesn't work, the next likely
step is to probably just declare PdfScribe as not Windows 10 compatible and
put it into maintenance mode for users still using Windows 7/8.

**Comment by agustindelaroza** [comment] 2020-01-09 12:26
I've find a solution that works in all cases! 
Just set the printer to use print spooler ( it was created to print directly by default).
Do you know of any way to enforce this setting in the printer installation process?

**Comment by agustindelaroza** [comment] 2020-01-09 17:04
Done.
In Class PdfScribeInstaller, function AddPdfScribePrinter()
        replace this value
"            pdfScribePrinter.Attributes = 0x00000040;"
with this value
"            pdfScribePrinter.Attributes = 0x0000001;"
This will create the printer in print spool mode

**Comment by stchan** [comment] 2020-01-29 03:49
I'm cautiously optimistic that this may be a viable work around. There was a related earlier issue #14 that was caused by the printer attributes being set to 0x2 (explicit direct printing). Changing the value to x40 (local printer) fixed the issue for some, but not all (hence this issue, #17). I'll need to test this on a few more installs before issuing a new release - probably in a couple of weeks as I'm pretty busy right now.

For anyone else who wants to try this workaround before a new installer is available -
Open Settings / Devices / Printers & scanners / PDF Scribe (click Manage) / Printer properties / Click "Advanced" tab / Click "Spool printer documents so program finishes printing faster" / Click "Start print after the last page is spooled" - then reboot and try to print (restarting the printer spooler service is not enough). 

note that you have to select "Start printing after the last page is spooled" - "Start printing immediately" won't work, even though you're still using the spooler.

Thanks for looking into this, and putting the time in.

**Comment by agmachadoicagr** [comment] 2020-02-03 14:00
I don't know if it will help but It can be a permissions problem when configuring the port. 
We have made it work after executing  a console with privileges  an run "rundll32 printui.dll PrintUIEntry / p / n "PDF Scribe" command  then  ports > configure and apply

**Comment by stchan** [comment] 2020-03-16 05:13
I tested 1.0.8 on a few different 1903/1909 installs (with latest patches) - they all seemed to work, so at this point there's 2 possibilities -

1) Just luck, as not everyone had this issue.
2) There were some changes made to Windows 1903/09 that fixed the issue.

I don't have an way of easily knowing which one is the reason why 1.0.8 started working again.

However, I will take your suggestion of setting a default of "Start printing after last page is spooled" with the installer as this may help with older builds (on 1903/09 this setting does not seem to matter - either setting works with a 1.0.8 install) and create a release 1.0.9 with those defaults. Permissions should not be an issue as the installer requires admin rights.

**Comment by trilok54660** [comment] 2020-03-25 10:40
This issue happenes if you login through ACTIVE DIRECTORY user

**Comment by stchan** [comment] 2020-03-28 05:49
I've found that this also happens with local users other than the user that did the installation - even if the other user is a member of the local Administrators group.  I'm not going to do any further investigation, and when I'm less busy with the day job (this could be a considerable time),  just work on replacing Redmon with another port monitor (most likely mfilemon) - of course this should not discourage anyone else from looking into it.

**Comment by zs-doron** [comment] 2020-06-25 12:26
Redmon has the following function to find a token to start the process:

    /* Retrieve the security token for the user we wish to impersonate */
    /* Thanks to Guy Hachlili at Cogniview for this code */
    /* This may pick the wrong session if the user is logged in twice */
    HANDLE get_token_for_user(LPCTSTR pUsername)
    {
        DWORD dwProcesses[128], dwProcs;
        HANDLE hToken, hFullToken = NULL;

        /* no user */
        if (pUsername == NULL)
	    return NULL;

        /* Go over the list for running processes, and find one which */
        /* has the same user */
        if (EnumProcesses(dwProcesses, sizeof(DWORD)*128, &dwProcs)) {
	    DWORD i;
    	for (i=0;(hFullToken == NULL) && (i<min(dwProcs, 128));i++) {
	        HANDLE hProc = 
    		OpenProcess(PROCESS_QUERY_INFORMATION|PROCESS_VM_READ, 
    		FALSE, dwProcesses[i]);
    	    if (hProc != NULL) {

For some reason, only the first 128 processes are considered in the loop which is an issue if the first 128 processes are not running as the print job's user.

clawmon and MFilemon require you to store your Windows credentials in the configuration which is not a good idea. These credentials are used to logon and create the process as your user.

**Comment by stchan** [comment] 2020-07-14 01:27
Thanks for looking into this. I haven't attempted to build Redmon, so I've never peeked under the hood to see what it was up to. Another thing to check when I come back around is are there any Redmon forks that may have fixed this issue.

> 
> 
> Redmon uses the following function to find a token to start the process:
> 
> ```
> /* Retrieve the security token for the user we wish to impersonate */
> /* Thanks to Guy Hachlili at Cogniview for this code */
> /* This may pick the wrong session if the user is logged in twice */
> HANDLE get_token_for_user(LPCTSTR pUsername)
> {
>     DWORD dwProcesses[128], dwProcs;
>     HANDLE hToken, hFullToken = NULL;
> 
>     /* no user */
>     if (pUsername == NULL)
>     return NULL;
> 
>     /* Go over the list for running processes, and find one which */
>     /* has the same user */
>     if (EnumProcesses(dwProcesses, sizeof(DWORD)*128, &dwProcs)) {
>     DWORD i;
> 	for (i=0;(hFullToken == NULL) && (i<min(dwProcs, 128));i++) {
>         HANDLE hProc = 
> 		OpenProcess(PROCESS_QUERY_INFORMATION|PROCESS_VM_READ, 
> 		FALSE, dwProcesses[i]);
> 	    if (hProc != NULL) {
> ```
> 
> For some reason, only the first 128 processes are considered in the loop which is an issue if the first 128 processes are not running as the print job's user.
> 
> clawmon and MFilemon require you to store your Windows credentials in the configuration which is not a good idea. These credentials are used to logon and create the process as your user.

**Comment by tahoop** [comment] 2020-11-25 16:29
I am running into this issue as well.  It was broke on one Win10 system, Win updates applied, and it worked for a few days and back to being broke.  When checked in task manager, the driver is sitting in the background processes (as expected from what is explained above).  I set up the build environment for Redmon DLL and made the proposed change to the process array.  I used 1024 as the size since that was used in a Microsoft code sample, it did not fix it.  There is a deeper issue driving this.

**Comment by zs-doron** [comment] 2020-11-25 21:00
> 
> 
> I am running into this issue as well. It was broke on one Win10 system, Win updates applied, and it worked for a few days and back to being broke. When checked in task manager, the driver is sitting in the background processes (as expected from what is explained above). I set up the build environment for Redmon DLL and made the proposed change to the process array. I used 1024 as the size since that was used in a Microsoft code sample, it did not fix it. There is a deeper issue driving this.

Have you tried adding log outputs to `get_token_for_user` to see if the issue is caused by not finding a token? You can use `write_string_to_log` to create log entries (in the registry LogFileDebug and LogFileName have to be set).

(I assume you have noticed that not just the array size, but also the loop have to be adjusted)

**Comment by tahoop** [comment] 2020-11-25 21:07
I changed both the size and loop counter to 1024 so good there.  As for logging, that is the direction I have been going.  I set the registry keys but not getting the log written out.  Digging through that.  I suspected as well that the token is not being found.  I did find in my case that admin users work fine, standard users do not.  Thanks for the response!

**Comment by zs-doron** [comment] 2020-11-26 09:58
> 
> 
> I did find in my case that admin users work fine, standard users do not.

If the issue is not related to the token not being found, it might be worth investigating whether there is a security policy prohibiting starting the UI process, e.g. https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/replace-a-process-level-token

**Comment by stchan** [comment] 2020-11-26 21:53
Thanks for looking into this - I haven't had time to do anything for this
project for about a year now. If you can successfully build Redmon, could
you share links/quick how tos on which DDKs need to be downloaded, and
which version of VC++ you used to build? It could help draw more people
into trying to troubleshoot.

Again, thanks you guys for looking into this - I appreciate it.

PS - If you're Americans (or living in the USA), Happy Turkey day!

**Comment by tahoop** [comment] 2020-11-30 14:35
stchan, thanks for your hard work and providing this project to the community.  I was able to rebuild Redmon using VS 2010 and the DDK version 7600.16385.1.  I had to update the make file for the respective paths on my machine.  Don't forget to run the vcvarsall batch file to build from the command line.  It took around 90 minutes to get the environment up.  

The process count fix did resolve the issue on one computer.  I'll test on two other systems this afternoon.  I did find out the hard way that the DLL is copied to and used from the system32 directory (not from the install folder where a copy exists).  If it checks out on these other systems, I'll push the new DLL to the repository.

**Comment by tahoop** [comment] 2020-12-01 14:14
[redmon64pdfscribe.zip](https://github.com/stchan/PdfScribe/files/5623071/redmon64pdfscribe.zip)

Attached is the rebuilt redmon dll using a process list size of 1024.  Of the three systems that exhibited the issue, the new build fixed it in all cases.  The code can be improved upon to get the process list size and use that when requesting and iterating the list but the change I made should work ok for most instances.

**Comment by stchan** [comment] 2021-01-13 06:30
closing this since there've been no reports of problems a month later

**Comment by chuongmep** [comment] 2021-02-02 09:19
I have same problem  windows 10 version 1909 but it working in windows 10 20H2, please open again.

**Comment by stchan** [comment] 2021-02-07 05:21
This is going to require getting the redmon source code successfully compiled before  any further investigation can continue. I can't make any promises as to when I can get around to this, but in the mean time people should continue reporting problems here - and with as much detail as possible.

**Comment by mca0815** [comment] 2021-05-01 02:59
Increasing the search for processes from 128 to 1024 fixes the problem most of the times. However I experienced one case where it still didn't help. But increasing it to 4096 did.

Here is a version that iterates up to 4096 processes;
[redmon64.zip](https://github.com/stchan/PdfScribe/files/6408742/redmon64.zip)

I was able to set up a build environments doing the following steps:

1. Install Visual Studio 2019 Community Edition, (I used version 14.28.29910)
2. Install Windows SDK. (I used version 10.0.19041.0)
3. Install Driver Driver Kit (WDK formerly DDK) (I used version 10.0.19041.0)
You will find all three download links here:
https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk (Step "1", "1.5" and "2").
4. If you want to be able to do a "make all" you will also need to install to the HTML Help Workshop.
Unfortunately Microsoft broke its download link mentioned here:
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/microsoft-html-help-downloads
So you will have to use archive.org:
http://web.archive.org/web/20160201063255/http://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe
m-(

In order to build Redmon:
1. Replace the original redmon.mak with [this](https://gist.github.com/mca0815/2679c8265e7b9ecec4a82d639373d425) one attached. (You may need to adjust the DDKVER variable if you installed a different WDS/WDK version than 10.0.19041.0. If you use Visual Studio Professional instead of Community Edition change the VS_EDITION variable.)
2. Open a cmd and cd to the source dir.
3. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\nmake.exe" /f redmon.mak all
(If needed change "14.28.29910" and "Community" to the Visual Studio version and edition, you are using.)

**Comment by stchan** [comment] 2021-05-04 23:24
Thanks for doing the work on this - over the next couple of weeks I'll review the changes, try to build, and put together a new release. In the meantime, if anyone gives the new dll a try, report your results here.

**Comment by pradeepngupta** [comment] 2021-07-04 10:11
Hi,
I am using this PDFScribe and extended to redirect the pdf file created to a windows printer using mswinpr2 Ghostscript command.
String[] ghostScriptArguments = {"-empty", "-dPrinted", "-dBATCH", "-dNOPAUSE", "-dNOSAFER", "-dNOINTERPOLATE", "-dNOCIE","-dNumCopies=1", "-sDEVICE=mswinpr2", String.Format("-sOutputFile=%printer%{0}", printerName),"-f", pdfFilename}; GhostScript.CallAPI(ghostScriptArguments);

It is running good.
But found an issue on Windows 10, when an user sign out and sign in. That time if any doc printed with my extended pdfscribe, it is getting stuck at the above ghostscript call to redirect the pdf file.
Moreover, the time taken to create PDF is around 4-5 seconds whereas in normal scenarios like after system restart, it usually takes 1-2 seconds.

My Other Observation:
On User Sign out & sign in, and then if print to my extended virtual printer, I have taken the Redmon port logs and found the below differences: 
a) REDMON_SESSIONID value will be 1 or incremented value, while on system restart the session id value is 0 (ie Admin access) b) The APPDATA directory is pointed to C:\Windows\system32\config\systemprofile\AppData\Roaming whereas it was C:\Users<Username>\AppData\Roaming on System restart. 
c) The USERPROFILE value is pointed to C:\Windows\system32\config\systemprofile.

I though this might be due to this issue of running redmon as system user.

Moreover, i though to replace the redmonpdfscribe.dll with official redmon.dll, but this does not worked as a straight forward.

Could anyone help in this regards? 
Let me know if i have create report this as a separate issue?

**Comment by stchan** [comment] 2021-07-07 16:15
Open a new issue if you want to ask for help on this. Since you've made modifications, I suggest creating a fork since the original code is not what is being referenced, and to allow others to build your changes.  Reference your fork in the new issue.

> Hi,
> I am using this PDFScribe and extended to redirect the pdf file created to a windows printer using mswinpr2 Ghostscript command.
> String[] ghostScriptArguments = {"-empty", "-dPrinted", "-dBATCH", "-dNOPAUSE", "-dNOSAFER", "-dNOINTERPOLATE", "-dNOCIE","-dNumCopies=1", "-sDEVICE=mswinpr2", String.Format("-sOutputFile=%printer%{0}", printerName),"-f", pdfFilename}; GhostScript.CallAPI(ghostScriptArguments);
> 
> It is running good.
> But found an issue on Windows 10, when an user sign out and sign in. That time if any doc printed with my extended pdfscribe, it is getting stuck at the above ghostscript call to redirect the pdf file.
> Moreover, the time taken to create PDF is around 4-5 seconds whereas in normal scenarios like after system restart, it usually takes 1-2 seconds.
> 
> My Other Observation:
> On User Sign out & sign in, and then if print to my extended virtual printer, I have taken the Redmon port logs and found the below differences:
> a) REDMON_SESSIONID value will be 1 or incremented value, while on system restart the session id value is 0 (ie Admin access) b) The APPDATA directory is pointed to C:\Windows\system32\config\systemprofile\AppData\Roaming whereas it was C:\Users\AppData\Roaming on System restart.
> c) The USERPROFILE value is pointed to C:\Windows\system32\config\systemprofile.
> 
> I though this might be due to this issue of running redmon as system user.
> 
> Moreover, i though to replace the redmonpdfscribe.dll with official redmon.dll, but this does not worked as a straight forward.
> 
> Could anyone help in this regards?
> Let me know if i have create report this as a separate issue?

**Comment by stchan** [comment] 2021-07-07 16:17
Release v1.1.0 includes the redmon changes from @mca0815 - I've been using it for the past couple of months without issue. If there are problems, open a new issue and reference #17.

**Closed by stchan** 2021-07-07 16:17 UTC
Labels: help wanted

**Comment by stchan** [comment] 2022-10-16 16:22
UPDATE: The source for redmon64pdfscribe is now included as a submodule reference.
