### ISSUE TITLE
No Output on Windows 10 1809

### ISSUE THREAD

**Issue by drseussofporn** [stchan/PdfScribe#16] opened 2019-06-14 21:36 UTC
This program used to work perfectly. After the Windows 10 1809 update (specifically, on 17763.529) PDF Scribe fails to generate any output. If you run the EXE directly from the Program Files directly, a blank PDF file is correctly generated. I first noticed the issue with a custom fork but it appears to affect the master branch of 1.0.7 as well.

**Comment by stchan** [comment] 2019-06-16 05:27
Unfortunately I'm not able to reproduce this on 17763.557 - release 1.0.7
is working fine for me on two different machines. You may want to turn on
Redmon logging to see what's going on with the port monitor. Also, it would
be helping if anyone else having this issue would chime in with info on
their environment.

You'll have to configure the PSCRIBE: port to write a log file from either
the Print Management app (not Devices and Printers), or running the
following command from an elevated command prompt:

rundll32 printui.dll,PrintUIEntry /p /n "PDF Scribe"

**Comment by stchan** [comment] 2019-06-17 03:49
possibly related to #9, #10, and maybe #14

**Comment by stchan** [comment] 2019-06-22 18:24
Applied help wanted label.

If anyone else is having this problem, chime in here - I'm trying to gather more information - so far, I haven't had this happen on any of my Windows 10 installs.

**Comment by cedrozor** [comment] 2019-06-25 18:50
I checked with my fork of PdfScribe (https://github.com/cedrozor/myrtille) and wasn't able to replicate the issue on a Windows 10 box fully updated. That said, I rely on version 1.0.5, modified for my needs, so this may not be relevant.

**Comment by drseussofporn** [comment] 2019-07-15 23:19
This issue might actually be two completely separate problems. I identified some custom code that was actually generating an error. The no output issue MAY also be related to the code, but it sounds like others have had similar issues.

**Comment by asycns** [comment] 2019-08-06 15:10
Reproduced on my machine. 
PDFScribe version 1.0.6. 
Windows 10 1903 Education (18362.239) 
Blank file: 
[1565103900872.pdf](https://github.com/stchan/PdfScribe/files/3472898/1565103900872.pdf)
I developed my software based on 1.0.6 last year and my program began to generate blank page after upgrading to 1903.

**Comment by asycns** [comment] 2019-08-06 15:40
And I also found a very strange problem. I added some forms and when I try to close application, it will hide to background. I think the two issues may be related to system bug but I can't find a line that causes these, even debugging line by line.

**Comment by drseussofporn** [comment] 2019-08-22 19:52
Confirmed that this issue is present on 1903 as well; we're definitely seeing this problem relate to redmon running as the system user. I have successfully installed [clawmon](https://github.com/clawsoftware/clawmon) and configured it to pipe the output to PDFScribe.exe and everything works as expected. It looks like some work just needs to be done on the implementation of redmon for PDFScribe.

**Comment by stchan** [comment] 2019-08-22 20:22
Thanks for the update - I was wondering if mfilemon would be a suitable replacement for Redmon - looks like I'll have to consider that heavily now that you've confirmed it works. 

If you've confirmed this issue is the same as #17 (running as system user), can you close this one, and make a comment on #17 that they were the same?  Thanks.

**Closed** 2019-08-22 20:32 UTC
Labels: help wanted
